name: Build and publish

on:
  push:
    branches:
      - 'main'

jobs:
  build_number:
    name: Generate build number
    runs-on: ubuntu-latest
    outputs:
      number: ${{ steps.build_out.outputs.number }}
      number_wearos: ${{ steps.wearos_out.outputs.number_wearos }}
    steps:
      - name: Generate build number
        id: buildnumber
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Set output for simple build'
        id: build_out
        run: |
          echo "number=${{ steps.buildnumber.outputs.build_number }}" >> $GITHUB_OUTPUT
  build_release:
    name: Build AAB and APK
    runs-on: ubuntu-latest
    needs: [ build_number ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Set up JDK 1.17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build release
        env:
          ORG_GRADLE_PROJECT_version_code: ${{ needs.build_number.outputs.number }}
        run: ./gradlew assembleRelease bundleRelease
      - name: Sign AAB
        id: sign_aab
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: composeApp/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_ALIAS_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
      - name: Sign APK
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: composeApp/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_ALIAS_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
      - name: Copy artifacts
        id: artifacts_copy
        run: |
          mkdir artifacts
          cp ${{ steps.sign_aab.outputs.signedReleaseFile }} artifacts/busystatusbar.aab
          cp ${{ steps.sign_apk.outputs.signedReleaseFile }} artifacts/busystatusbar.apk
          cp composeApp/build/outputs/mapping/release/mapping.txt artifacts/mapping.txt
          echo "path=artifacts/" >> $GITHUB_OUTPUT
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ${{ steps.artifacts_copy.outputs.path }}
  build_desktop:
    name: "Build desktop app"
    uses: ./.github/workflows/call-desktop-build.yml
  upload_to_github:
    name: Upload to Github Releases
    runs-on: ubuntu-latest
    needs: [ build_release, build_number, build_desktop ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: actions/download-artifact@v4
        id: download
        with:
          name: artifacts
          path: download/artifacts
      - uses: actions/download-artifact@v4
        id: download-desktop
        with:
          name: ${{ needs.build_desktop.outputs.ARTIFACTS_NAME }}
          path: download/artifacts
      - name: 'Copy artifacts'
        id: artifacts_copy
        run: |
          mkdir artifacts
          cp ${{steps.download.outputs.download-path}}/* artifacts/
          echo "path=artifacts/" >> $GITHUB_OUTPUT
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: Prepare mapping
        id: mappings
        run: |
          mkdir mappings
          mv "${{ steps.artifacts_copy.outputs.path }}/mapping.txt" mappings/
          zip -qq -r mappings.zip mappings
          echo "archive=mappings.zip" >> $GITHUB_OUTPUT
      - name: Prepare other builds
        id: other
        run: |
          mkdir other
          mv ${{ steps.artifacts_copy.outputs.path }}/*.aab other/
          zip -qq -r other.zip other
          echo "archive=other.zip" >> $GITHUB_OUTPUT
      - name: 'Set variables'
        id: vars
        run: |
          export $(cat .github/workflows/version.env | xargs)
          echo "major_version=0.0" >> $GITHUB_OUTPUT
          echo "minor_version=${{ needs.build_number.outputs.number }}" >> $GITHUB_OUTPUT
      - name: Artifact build beautifier
        id: beautifier
        run: |
          mv ${{ steps.artifacts_copy.outputs.path }}/busystatusbar.apk ${{ steps.artifacts_copy.outputs.path }}/busystatusbar-${{ steps.vars.outputs.major_version }}.${{ steps.vars.outputs.minor_version }}.apk
      - name: Create internal Release
        id: create_internal_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ steps.mappings.outputs.archive }}
            ${{ steps.other.outputs.archive }}
            ${{ steps.artifacts_copy.outputs.path }}/busystatusbar-${{ steps.vars.outputs.major_version }}.${{ steps.vars.outputs.minor_version }}.apk
            ${{steps.download-desktop.outputs.download-path}}/*
          tag_name: ${{ steps.vars.outputs.major_version }}.${{ steps.vars.outputs.minor_version }}
          name: Busy Status Bar ${{ steps.vars.outputs.major_version }}.${{ steps.vars.outputs.minor_version }}
          draft: false
