name: Build and publish

on:
  push:
    branches:
      - 'main'

jobs:
  build_number:
    name: Generate build number
    runs-on: ubuntu-latest
    outputs:
      number: ${{ steps.build_out.outputs.number }}
      number_wearos: ${{ steps.wearos_out.outputs.number_wearos }}
    steps:
      - name: Generate build number
        id: buildnumber
        uses: onyxmueller/build-tag-number@4a0c81c9af350d967032d49204c83c38e6b0c8e4 # v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Set output for simple build'
        id: build_out
        run: |
          echo "number=${{ steps.buildnumber.outputs.build_number }}" >> $GITHUB_OUTPUT
  build_release:
    name: Build AAB and APK
    runs-on: ubuntu-latest
    needs: [ build_number ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: 'recursive'
      - name: Set up JDK 1.17
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build release
        env:
          ORG_GRADLE_PROJECT_version_code: ${{ needs.build_number.outputs.number }}
        run: ./gradlew assembleRelease bundleRelease
      - name: Sign AAB
        id: sign_aab
        uses: r0adkll/sign-android-release@349ebdef58775b1e0d8099458af0816dc79b6407 # v1
        with:
          releaseDirectory: instances/bsb/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_ALIAS_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
      - name: Sign APK
        id: sign_apk
        uses: r0adkll/sign-android-release@349ebdef58775b1e0d8099458af0816dc79b6407 # v1
        with:
          releaseDirectory: instances/bsb/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_ALIAS_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
      - name: Copy artifacts
        id: artifacts_copy
        run: |
          mkdir artifacts
          cp ${{ steps.sign_aab.outputs.signedReleaseFile }} artifacts/busystatusbar.aab
          cp ${{ steps.sign_apk.outputs.signedReleaseFile }} artifacts/busystatusbar.apk
          cp instances/bsb/build/outputs/mapping/release/mapping.txt artifacts/mapping.txt
          echo "path=artifacts/" >> $GITHUB_OUTPUT
      - name: Upload Artifacts
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4
        with:
          name: artifacts
          path: ${{ steps.artifacts_copy.outputs.path }}
  build_desktop:
    name: "Build desktop app"
    needs: [ build_number ]
    uses: ./.github/workflows/call-desktop-build.yml
    with:
      BUILD_NUMBER: ${{ needs.build_number.outputs.number }}
  upload_to_github:
    name: Upload to Github Releases
    runs-on: ubuntu-latest
    needs: [ build_release, build_number, build_desktop ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: 'recursive'
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        id: download
        with:
          name: artifacts
          path: download/artifacts
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        id: download-desktop
        with:
          name: ${{ needs.build_desktop.outputs.ARTIFACTS_NAME }}
          path: download/artifacts-desktop
      - name: 'Copy artifacts'
        id: artifacts_copy
        run: |
          mkdir artifacts
          cp ${{steps.download.outputs.download-path}}/* artifacts/
          echo "path=artifacts/" >> $GITHUB_OUTPUT
      - name: Install zip
        uses: montudor/action-zip@a8e75c9faefcd80fac3baf53ef40b9b119d5b702 # v1
      - name: Prepare mapping
        id: mappings
        run: |
          mkdir mappings
          mv "${{ steps.artifacts_copy.outputs.path }}/mapping.txt" mappings/
          zip -qq -r mappings.zip mappings
          echo "archive=mappings.zip" >> $GITHUB_OUTPUT
      - name: Prepare other builds
        id: other
        run: |
          mkdir other
          mv ${{ steps.artifacts_copy.outputs.path }}/*.aab other/
          zip -qq -r other.zip other
          echo "archive=other.zip" >> $GITHUB_OUTPUT
      - name: 'Set variables'
        id: vars
        run: |
          export $(cat .github/workflows/version.env | xargs)
          echo "major_version=1.0" >> $GITHUB_OUTPUT
          echo "minor_version=${{ needs.build_number.outputs.number }}" >> $GITHUB_OUTPUT
      - name: Artifact build beautifier
        id: beautifier
        run: |
          mv ${{ steps.artifacts_copy.outputs.path }}/busystatusbar.apk ${{ steps.artifacts_copy.outputs.path }}/busystatusbar-${{ steps.vars.outputs.major_version }}.${{ steps.vars.outputs.minor_version }}.apk
      - name: Create internal Release
        id: create_internal_release
        uses: softprops/action-gh-release@e7a8f85e1c67a31e6ed99a94b41bd0b71bbee6b8 # v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ steps.mappings.outputs.archive }}
            ${{ steps.other.outputs.archive }}
            ${{ steps.artifacts_copy.outputs.path }}/busystatusbar-${{ steps.vars.outputs.major_version }}.${{ steps.vars.outputs.minor_version }}.apk
            ${{steps.download-desktop.outputs.download-path}}/*
          tag_name: ${{ steps.vars.outputs.major_version }}.${{ steps.vars.outputs.minor_version }}
          name: Busy Status Bar ${{ steps.vars.outputs.major_version }}.${{ steps.vars.outputs.minor_version }}
          draft: false
          body: |
            Web version: [https://busy-app.github.io/Android/](https://busy-app.github.io/Android/)
            
            Doesn't work on Safari until this [PR by Apple](https://github.com/WebKit/WebKit/pull/31854) is released
            
